.Dd December 13 2024
.Dt libglog 3
.Os
.
.Sh NAME
.Nm glog__unreachable
.Nd Print message to unreachable level
.
.Sh LIBRARY
.Xr libglog 3
(-lglog)
.
.Sh SYNOPSIS
.In glog.h
.Bd -literal
#define glog__unreachable(logger, fmt) glog__putf(logger, &glog__unreachable_level, fmt)
.Ed
.
.Sh DESCRIPTION
Print message to unreachable level.
.Pp
Unreachable logging level is 2000
.Pp
Print messages about unreachable situations.
.
.Sh NOTES
This macro and logging level crashing app.
.
.Sh EXAMPLES
.Bd -literal
#include <glog.h>

int main()
{
	struct glog__logger logger = {0};
	glog__logger_from_prefix(&logger, "logger");

	glog__unreachable(&logger, "Unreachable message");

	return 0;
}
.Ed
.
.Sh SEE ALSO
.Xr libglog 3
.Xr glog__chaos 3
.Xr glog__chaosf 3
.Xr glog__trace 3
.Xr glog__tracef 3
.Xr glog__debug 3
.Xr glog__debugf 3
.Xr glog__info 3
.Xr glog__infof 3
.Xr glog__warn 3
.Xr glog__warnf 3
.Xr glog__error 3
.Xr glog__errorf 3
.Xr glog__die 3
.Xr glog__dief 3
.Xr glog__unreachable 3
.Xr glog__unreachablef 3
.Xr glog__logger_from_prefix 3
.
.Sh AUTHORS
.An gimura2022 Aq Mt gimura0001@gmail.com
